const keyCodes = {
  'KeyQ': false,
  'KeyW': false,
  'KeyE': false,
  'Digit2': false,
  'Digit3': false,
  'KeyR': false,
  'KeyT': false,
  'KeyY': false,
  'KeyU': false,
  'Digit5': false,
  'Digit6': false,
  'Digit7': false,
  'KeyI': false,
  'KeyO': false,
  'KeyP': false,
  'Digit9': false,
  'Digit0': false,
  'KeyZ': false,
  'KeyX': false,
  'KeyC': false,
  'KeyV': false,
  'KeyS': false,
  'KeyD': false,
  'KeyF': false,
  'KeyB': false,
  'KeyN': false,
  'KeyM': false,
  'KeyH': false,
  'KeyJ': false,
  'Comma': false,
  'Period': false,
  'Slash': false,
  'Quote': false,
  'KeyL': false,
  'Semicolon': false,
  'BracketLeft': false
};

export { keyCodes };
